apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-deployment
  labels:
    app: springboot
spec:
  replicas: 2
  selector:
    matchLabels:
      app: springboot
  template:
    metadata:
      labels:
        app: springboot
    spec:
      containers:
      - name: my-book-management
        image: giahai99/javaapp:2.0
        ports:
        - containerPort: 8080
