---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-deployment
  labels:
    app: springboot
spec:
  replicas: 2
  selector:
    matchLabels:
      app: springboot
  template:
    metadata:
      labels:
        app: springboot
    spec:
      containers:
      - name: my-book-management
        image: giahai99/javaapp:3.0
        ports:
          - containerPort: 8080
        env:    # Setting Environmental Varialbles
          - name: DB_HOST  # Setting Database host address
            valueFrom:
              configMapKeyRef:
                name: mysql-configmap
                key: db_host
          - name: DB_NAME  # Setting Database name
            valueFrom:
              configMapKeyRef:
                name: mysql-configmap
                key: db_name
          - name: DB_USERNAME  # Setting Database username
            valueFrom:
              secretKeyRef:
                name: db-user-pass
                key: username
          - name: DB_PASSWORD  # Setting Database password
            valueFrom:
              secretKeyRef:
                name: db-user-pass
                key: password
---
